# Generated by Django 4.1.3 on 2022-12-08 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0009_alter_pet_options_pet_race_pet_sex_pet_weight_and_more'),
        ('vaccine', '0010_alter_vaccine_options_alter_vaccine_name'),
        ('vaccination', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaccination',
            options={'verbose_name': 'Vacunación', 'verbose_name_plural': 'Vacunaciones'},
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='date_placed',
            field=models.DateField(verbose_name='Fecha colocación'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.pet', verbose_name='Mascota'),
        ),
        migrations.AlterField(
            model_name='vaccination',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccine.vaccine', verbose_name='Vacuna'),
        ),
    ]
