# Generated by Django 4.1.3 on 2022-12-08 16:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0009_alter_pet_options_pet_race_pet_sex_pet_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.CharField(choices=[('ML', 'Macho'), ('FM', 'Hembra')], max_length=2, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.SmallIntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)], verbose_name='Peso'),
        ),
    ]
