# Generated by Django 4.1.3 on 2022-12-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0010_alter_pet_sex_alter_pet_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='castrated',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
