# Generated by Django 4.1.3 on 2022-12-25 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('MO', 'Lunes'), ('TU', 'Martes'), ('WE', 'miercoles'), ('TH', 'Jueves'), ('FR', 'Viernes'), ('SA', 'Sabado'), ('SU', 'Domingo')], max_length=2, verbose_name='Dia')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Veterinario')),
            ],
        ),
    ]
