# Generated by Django 4.1.3 on 2022-12-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('availability', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='day',
            field=models.CharField(choices=[('MO', 'Lunes'), ('TU', 'Martes'), ('WE', 'Miercoles'), ('TH', 'Jueves'), ('FR', 'Viernes'), ('SA', 'Sabado'), ('SU', 'Domingo')], max_length=2, verbose_name='Dia'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='availability',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
