# Generated by Django 4.1.3 on 2022-12-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specie',
            options={'verbose_name': 'Especie', 'verbose_name_plural': 'Especies'},
        ),
        migrations.AlterField(
            model_name='specie',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
    ]
