# Generated by Django 4.1.3 on 2022-11-15 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('specie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specie.specie')),
            ],
        ),
    ]
