# Generated by Django 4.1.3 on 2022-12-08 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('specie', '0002_alter_specie_options_alter_specie_name'),
        ('race', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='race',
            options={'verbose_name': 'Raza', 'verbose_name_plural': 'Razas'},
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='race',
            name='specie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specie.specie', verbose_name='Especie'),
        ),
    ]
