# Generated by Django 4.1.3 on 2022-11-11 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0006_alter_pet_user'),
        ('vaccine', '0002_vaccination'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination',
            name='pet',
            field=models.ForeignKey(default=13, on_delete=django.db.models.deletion.CASCADE, to='pet.pet'),
            preserve_default=False,
        ),
    ]
