# Generated by Django 4.1.3 on 2022-11-14 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0004_vaccination_created_vaccination_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination',
            name='date_placed',
            field=models.DateField(default=datetime.datetime(2022, 11, 14, 14, 42, 27, 302064, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
