# Generated by Django 4.1.3 on 2022-11-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0005_vaccination_date_placed'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccination',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
