# Generated by Django 4.1.3 on 2022-11-15 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0006_vaccination_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vaccination',
        ),
    ]
