# Generated by Django 4.1.3 on 2022-11-15 16:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0007_delete_vaccination'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2022, 11, 15, 16, 49, 47, 594168, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
