# Generated by Django 4.1.3 on 2022-11-15 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0008_vaccine_expiration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaccine',
            name='expiration_date',
        ),
    ]
