# Generated by Django 4.1.3 on 2022-11-16 21:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_birth_date_user_document_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
