# Generated by Django 4.1.3 on 2022-11-18 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_id_number_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_number',
            field=models.IntegerField(unique=True),
        ),
    ]
