# Generated by Django 4.1.3 on 2022-12-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_user_id_number_alter_user_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=90, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MA', 'Masculino'), ('FE', 'Femenino'), ('UN', 'Indefinido'), ('OT', 'Otro')], max_length=2, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_number',
            field=models.IntegerField(unique=True, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=90, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(verbose_name='Teléfono'),
        ),
    ]
