# Generated by Django 4.1.3 on 2022-12-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_user_options_alter_user_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_vet_user',
            field=models.BooleanField(default=False),
        ),
    ]
