# Generated by Django 4.1.3 on 2022-12-25 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_user_is_vet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_vet_user',
            field=models.BooleanField(default=False, verbose_name='Es Veterinario'),
        ),
    ]
