# Generated by Django 4.1.3 on 2022-11-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0001_initial'),
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='health',
            name='vaccines',
            field=models.ManyToManyField(to='vaccine.vaccine'),
        ),
    ]
