# Generated by Django 4.1.3 on 2022-11-13 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_health_vaccines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='health',
            name='vaccines',
        ),
    ]
